<?php

/*
 * Implements hook_menu_alter().
 */
function vandis_main_menu_alter(&$items) {
  // Disable node page
  if (isset($items['node'])) {
    $items['node']['access callback'] = FALSE;
  }
}

/**
 * Implements hook_menu().
 */
function vandis_main_menu() {
  $items = array();
  // Page for vandis settings
  $items['admin/config/system/vandis-admin'] = array(
    'title' => 'vandis settings',
    'description' => 'Settings for vandis',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vandis_main_admin_settings'),
    'access arguments' => array('edit vandis settings'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function vandis_main_permission() {
  return array(
    'edit vandis settings' => array(
      'title' => t('Edit vandis Settings'),
      'description' => t('Is able to edit the vandis settings'),
    ),
  );
}

/*
* Admin settings page, uses a hook to get settings fields
*/
function vandis_main_admin_settings($form, &$form_state) {
  // Run a hook to fetch all vandis setting parts
  $forms = module_invoke_all('vandis_main_settings_fields', $form, $form_state);
  // Loop through results and put in form
  foreach ($forms as $key => $hookform) {
    $form[$key] = $hookform;
    $form[$key]['#collapsible'] = TRUE;
    $form[$key]['#collapsed'] = TRUE;
  }
  $form['#submit'][] = 'vandis_main_admin_settings_submit';
  $form['#validate'][] = 'vandis_main_admin_settings_validate';
  // Return as settings form
  return system_settings_form($form);
}

function vandis_main_admin_settings_submit($form, &$form_state) {
  $return = module_invoke_all('vandis_main_settings_fields_submit', $form, $form_state);
  if ($return) {
    $form_state = $return;
  }
}

function vandis_main_admin_settings_validate($form, &$form_state) {
  $return = module_invoke_all('vandis_main_settings_fields_validate', $form, $form_state);
  if ($return) {
    $form_state = $return;
  }
}

function vandis_main_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['height'] = 200;
  }
}

function vandis_main_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['3span'] = array(
    'label' => t('Appartementen overzicht'),
    'custom settings' => TRUE,
  );
}

function vandis_main_preprocess_node(&$vars) {
  if ($vars['view_mode'] == '3span') {
    $vars['theme_hook_suggestion'][] = 'node__3span';
  }
}
